<a href="https://colab.research.google.com/github/jhine/TIL/blob/master/%EB%84%98%ED%8C%8C%EC%9D%B4_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이

## 2차원 배열의 인덱싱과 슬라이싱
- 인덱싱은 다음과 같이 표현 됩니다. 
$$
  array[행, 열]
$$

- 슬라이스는 행과 열을 각각 정의할 수 있습니다. 

$$
  array[행시작:행끝, 열시작:열끝]
$$

### 2차원 배열의 인덱싱과 슬라이싱 연습

In [4]:
import numpy as np
arrN = np.arange(1, 31).reshape(3, 10)
arrN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [7]:
# 주어진 배열에서 다음의 수 들을 인덱싱 또는 슬라이스 해보시면 됩니다. 

# 16
display(arrN[1,5])
# 29
display(arrN[2,8])
# 14, 15, 16
display(arrN[1,3:6])
# 18, 28
display(arrN[1:3,7])
# 9, 10, 19, 20


16

29

array([14, 15, 16])

array([18, 28])

array([[ 9, 10],
       [19, 20]])

In [38]:
arrn = np.arange(1, 51).reshape(5, 10)
arrn

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [42]:
# 14, 15, 16, 17, 24, 25, 26, 27, 34, 35, 36, 37
display(arrn[1:4,3:7 ])


# 12, 22, 32

array([[14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37]])

## 배열 생성 

### 배열 생성 연습

In [44]:
#중복되지 않는 무작위 수열 생성
arr = np.arange(1, 45)
np.random.choice(arr, size=6, replace=False)

array([17, 32, 26, 30, 35, 37])